name: DicomVmac
options:
  bundleIdPrefix: com.mystudio
  deploymentTarget:
    macOS: "14.0"
  xcodeVersion: "26.1"
  generateEmptyDirectories: true
  createIntermediateGroups: true

settings:
  base:
    ARCHS: "arm64 x86_64"
    SWIFT_VERSION: "6"
    MACOSX_DEPLOYMENT_TARGET: "14.0"
    CLANG_ENABLE_MODULES: YES
    ENABLE_BITCODE: NO
    CODE_SIGN_STYLE: Automatic
    DEVELOPMENT_TEAM: ""

packages:
  GRDB:
    url: https://github.com/groue/GRDB.swift
    from: "7.0.0"

targets:
  DicomVmac:
    type: application
    platform: macOS
    sources:
      - path: DicomVmac
        excludes:
          - "**/*.entitlements"
    dependencies:
      - target: DicomCore
        link: true
        embed: false
      - package: GRDB
      - sdk: Metal.framework
      - sdk: MetalKit.framework
      - sdk: AppKit.framework
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.mystudio.DicomVmac
        PRODUCT_NAME: DicomVmac
        INFOPLIST_FILE: DicomVmac/Info.plist
        CODE_SIGN_ENTITLEMENTS: DicomVmac/DicomVmac.entitlements
        SWIFT_OBJC_BRIDGING_HEADER: DicomVmac/DicomVmac-Bridging-Header.h
        LD_RUNPATH_SEARCH_PATHS: "@executable_path/../Frameworks"
        COMBINE_HIDPI_IMAGES: YES
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        HEADER_SEARCH_PATHS:
          - "$(SRCROOT)/DicomCore/include"
        LIBRARY_SEARCH_PATHS:
          - "$(SRCROOT)/dcmtk-universal/lib"
        OTHER_LDFLAGS:
          - "-ldcmdata"
          - "-ldcmnet"
          - "-ldcmimgle"
          - "-ldcmimage"
          - "-ldcmjpeg"
          - "-ldcmjpls"
          - "-ldcmtkcharls"
          - "-lijg8"
          - "-lijg12"
          - "-lijg16"
          - "-ldcmiod"
          - "-ldcmfg"
          - "-ldcmseg"
          - "-ldcmsr"
          - "-ldcmtls"
          - "-ldcmqrdb"
          - "-ldcmpstat"
          - "-ldcmwlm"
          - "-ldcmrt"
          - "-ldcmtract"
          - "-ldcmect"
          - "-ldcmpmap"
          - "-ldcmdsig"
          - "-ldcmxml"
          - "-lcmr"
          - "-li2d"
          - "-loflog"
          - "-loficonv"
          - "-lofstd"
          - "-lz"
          - "-lc++"
      configs:
        Debug:
          SWIFT_OPTIMIZATION_LEVEL: "-Onone"
          SWIFT_ACTIVE_COMPILATION_CONDITIONS: DEBUG
          MTL_ENABLE_DEBUG_INFO: INCLUDE_SOURCE
          GCC_OPTIMIZATION_LEVEL: "0"
        Release:
          SWIFT_OPTIMIZATION_LEVEL: "-O"
          MTL_ENABLE_DEBUG_INFO: NO
          GCC_OPTIMIZATION_LEVEL: s
          SWIFT_COMPILATION_MODE: wholemodule
    scheme:
      testTargets:
        - DicomVmacTests
      environmentVariables:
        - variable: METAL_DEVICE_WRAPPER_TYPE
          value: 1
          isEnabled: false

  DicomCore:
    type: library.static
    platform: macOS
    sources:
      - path: DicomCore/src
      - path: DicomCore/include
        headerVisibility: public
        type: folder
    settings:
      base:
        PRODUCT_NAME: DicomCore
        CLANG_CXX_LANGUAGE_STANDARD: c++17
        CLANG_CXX_LIBRARY: libc++
        HEADER_SEARCH_PATHS:
          - "$(SRCROOT)/DicomCore/include"
          - "$(SRCROOT)/DicomCore/internal"
          - "$(SRCROOT)/dcmtk-universal/include"
        LIBRARY_SEARCH_PATHS:
          - "$(SRCROOT)/dcmtk-universal/lib"
        GCC_SYMBOLS_PRIVATE_EXTERN: NO
        OTHER_CFLAGS: "-fvisibility=default"
      configs:
        Debug:
          GCC_OPTIMIZATION_LEVEL: "0"
          GCC_GENERATE_DEBUGGING_SYMBOLS: YES
        Release:
          GCC_OPTIMIZATION_LEVEL: s

  DicomVmacTests:
    type: bundle.unit-test
    platform: macOS
    sources:
      - path: DicomVmacTests
    dependencies:
      - target: DicomVmac
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.mystudio.DicomVmacTests
        INFOPLIST_FILE: ""
        GENERATE_INFOPLIST_FILE: YES
        HEADER_SEARCH_PATHS:
          - "$(SRCROOT)/DicomCore/include"
